<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKSQjoxL\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKSQjoxL/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKSQjoxL.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKSQjoxL\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKSQjoxL\App_KernelProdContainer([
    'container.build_hash' => 'KSQjoxL',
    'container.build_id' => '2a68b162',
    'container.build_time' => 1652446286,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKSQjoxL');
