<?php

namespace ContainerKSQjoxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.491rxCd.App\Entity\Newsletters\Users' shared service.
     *
     * @return \App\Entity\Newsletters\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.491rxCd": it references class "App\\Entity\\Newsletters\\Users" but no such service exists.');
    }
}
