<?php

namespace ContainerSDgf5RH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletters2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SorsgGd.App\Entity\Newsletters\Newsletters' shared service.
     *
     * @return \App\Entity\Newsletters\Newsletters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SorsgGd": it references class "App\\Entity\\Newsletters\\Newsletters" but no such service exists.');
    }
}
