<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8pzxe3I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8pzxe3I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8pzxe3I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8pzxe3I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8pzxe3I\App_KernelDevDebugContainer([
    'container.build_hash' => '8pzxe3I',
    'container.build_id' => 'e240eb97',
    'container.build_time' => 1652353063,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8pzxe3I');
